### ISSUE TITLE
Aria attributes error

### ISSUE THREAD

**Issue by markknol** [haxetink/tink_domspec#19]
I want to add this to `typedef GlobalAttr<Style>`:
```haxe
  @:html('aria-label') @:optional var ariaLabel(default, never):String;
  @:html('aria-labeledby') @:optional var ariaLabelledby(default, never):String;
  @:html('aria-describedby') @:optional var ariaDescribedby(default, never):String;
  @:html('aria-autocomplete') @:optional var ariaAutocomplete(default, never):String;
  @:html('aria-dropeffect') @:optional var ariaDropEffect(default, never):String;
  @:html('aria-hidden') @:optional var ariaHidden(default, never):Bool;
  @:html('aria-disabled') @:optional var ariaDisabled(default, never):Bool;
  @:html('aria-checked') @:optional var ariaChecked(default, never):Bool;
  @:html('aria-haspopup') @:optional var ariaHasPopup(default, never):Bool;
  @:html('aria-grabbed') @:optional var ariaGrabbed(default, never):Bool;
```
But I get this error:
```
type TType(tink.domspec.Tags,[]) has no fields
```
It specifically throws that error on the `Bool`s, with just the Strings it compiles nicely.

Using Haxe 4.0.5 / latest git tink_domspec

**Comment by back2dos** [comment]
Ok. I've moved this into its own type.

The "problem" is that aria attributes are not in fact JavaScript properties, meaning every coconut backend has to deal with it separately: coconut.react-dom just passes them on and react-dom applies them (via `setAttribute`), coconut.vdom applies them via `setAttribute`, coconut.html just outputs them like any other attribute.

I've updated `coconut.react-dom` to accept all aria attributes defined in `tink.domspec.Aria` (previously it supported less). For the time being `coconut.vdom` and `coconut.html` allow any attribute prefixed with `aria-`. This could also be restricted, but I don't want to make a breaking change at this time.

**Comment by markknol** [comment]
Sounds good, what do I have to update to make this work on my coconut.vdom project? Is coconut.vdom and tink_domspec enough?

**Comment by back2dos** [comment]
I'm not sure what exact problem you had experienced, but there never should've been one with `coconut.vdom`. As I said, it accepts any attribute starting with `aria-`. That's for example why `ProgressBar` in `coconut.bootstrap` is working just fine, despite using `aria-valuenow`, which was not among the attributes you've added.

**Comment by grepsuzette** [comment]
@markknol It's funny like you I worked on some bootstrap components for coconut (but I have much less than you, good work btw!) and went through the exact same reasoning as you for aria attrs, initially coming to tink_domspec.

So as back2dos said, in `coconut.vdom` there is a simple regex attribute names are matched against, and if it matches `aria-.*` they get short-circuited so that for coconut apps it absolutely doesn't matter whether these aria attributes are defined in `tink_domspec` or not. IIRC it is more or less the same as for attrs like `data-*` where there is no standard. For aria the attr names are actually standardized but there are like 51 possible attributes so I guess this is why coconut processes it the same.

**Comment by markknol** [comment]
Thanksss 🎉  If have have specific errors (which I think I had at first) Ill let you know.

@emugel Cool! Is there a repo for this? Maybe we can combine forces?

**Comment by grepsuzette** [comment]
No because it’s more of a studying project and minimal components so I could start my coconut appa, but will very likely collaborate to your project :) I have a Modal component that works, but it’s quite minimal at this point. When I come back on my coconut app I’ll clone your repo, right now my attention is on smtg else.
